//! Raw FFI bindings for the SQLite loadable-extension C API (`sqlite3ext.h`).
//!
//! Like `libsqlite3-sys`, the bindings are *pre-generated and committed* (see
//! `src/bindings.rs`, produced by bindgen from SQLite 3.51.2). This means the
//! normal build needs **no libclang** and no network access. To refresh them
//! after a SQLite header change, build with `--features regenerate` (which does
//! require libclang) and `src/bindings.rs` will be rewritten.
//!
//! Only types, structs and `SQLITE_*` constants are emitted — no function
//! declarations. A loadable extension must not link libsqlite3; instead it
//! dispatches every call through the `sqlite3_api_routines` table provided by
//! the host at load time.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]
// bindings.rs is machine-generated by bindgen; do not lint it.
#![allow(clippy::all)]

include!("bindings.rs");
