#include <sqlite3ext.h>
#include <stddef.h>
size_t vectorlite_sqlite_abi_layout(size_t index) {
  static const size_t layout[] = {
      sizeof(sqlite3_vtab),
      offsetof(sqlite3_vtab, pModule),
      offsetof(sqlite3_vtab, nRef),
      offsetof(sqlite3_vtab, zErrMsg),
      sizeof(sqlite3_vtab_cursor),
      offsetof(sqlite3_vtab_cursor, pVtab),
      sizeof(sqlite3_module),
      offsetof(sqlite3_module, iVersion),
      offsetof(sqlite3_module, xCreate),
      offsetof(sqlite3_module, xConnect),
      offsetof(sqlite3_module, xBestIndex),
      offsetof(sqlite3_module, xDisconnect),
      offsetof(sqlite3_module, xDestroy),
      offsetof(sqlite3_module, xOpen),
      offsetof(sqlite3_module, xClose),
      offsetof(sqlite3_module, xFilter),
      offsetof(sqlite3_module, xNext),
      offsetof(sqlite3_module, xEof),
      offsetof(sqlite3_module, xColumn),
      offsetof(sqlite3_module, xRowid),
      offsetof(sqlite3_module, xUpdate),
      offsetof(sqlite3_module, xFindFunction),
      offsetof(sqlite3_module, xRename),
      offsetof(sqlite3_module, xBegin),
      offsetof(sqlite3_module, xSync),
      offsetof(sqlite3_module, xCommit),
      offsetof(sqlite3_module, xRollback),
      offsetof(sqlite3_module, xSavepoint),
      offsetof(sqlite3_module, xRelease),
      offsetof(sqlite3_module, xRollbackTo),
      offsetof(sqlite3_module, xShadowName),
      sizeof(sqlite3_index_info),
      offsetof(sqlite3_index_info, nConstraint),
      offsetof(sqlite3_index_info, aConstraint),
      offsetof(sqlite3_index_info, nOrderBy),
      offsetof(sqlite3_index_info, aOrderBy),
      offsetof(sqlite3_index_info, aConstraintUsage),
      offsetof(sqlite3_index_info, idxNum),
      offsetof(sqlite3_index_info, idxStr),
      offsetof(sqlite3_index_info, needToFreeIdxStr),
      offsetof(sqlite3_index_info, orderByConsumed),
      offsetof(sqlite3_index_info, estimatedCost),
      offsetof(sqlite3_index_info, estimatedRows),
      offsetof(sqlite3_index_info, idxFlags),
      offsetof(sqlite3_index_info, colUsed),
      sizeof(sqlite3_api_routines),
      offsetof(sqlite3_api_routines, libversion_number),
      offsetof(sqlite3_api_routines, value_type),
      offsetof(sqlite3_api_routines, value_bytes),
      offsetof(sqlite3_api_routines, value_blob),
      offsetof(sqlite3_api_routines, value_text),
      offsetof(sqlite3_api_routines, value_int),
      offsetof(sqlite3_api_routines, value_int64),
      offsetof(sqlite3_api_routines, value_pointer),
      offsetof(sqlite3_api_routines, result_double),
      offsetof(sqlite3_api_routines, result_null),
      offsetof(sqlite3_api_routines, result_blob),
      offsetof(sqlite3_api_routines, result_text),
      offsetof(sqlite3_api_routines, result_error),
      offsetof(sqlite3_api_routines, result_pointer),
      offsetof(sqlite3_api_routines, malloc),
      offsetof(sqlite3_api_routines, free),
      offsetof(sqlite3_api_routines, declare_vtab),
      offsetof(sqlite3_api_routines, vtab_config),
      offsetof(sqlite3_api_routines, create_module_v2),
      offsetof(sqlite3_api_routines, create_function_v2),
      offsetof(sqlite3_api_routines, vtab_in),
      offsetof(sqlite3_api_routines, vtab_in_first),
      offsetof(sqlite3_api_routines, vtab_in_next),
      offsetof(sqlite3_api_routines, prepare_v2),
      offsetof(sqlite3_api_routines, finalize),
      offsetof(sqlite3_api_routines, bind_int64),
      offsetof(sqlite3_api_routines, bind_blob),
      offsetof(sqlite3_api_routines, bind_text),
      offsetof(sqlite3_api_routines, step),
      offsetof(sqlite3_api_routines, column_count),
      offsetof(sqlite3_api_routines, column_type),
      offsetof(sqlite3_api_routines, column_int64),
      offsetof(sqlite3_api_routines, column_blob),
      offsetof(sqlite3_api_routines, column_bytes),
      offsetof(sqlite3_api_routines, column_text),
      offsetof(sqlite3_api_routines, errmsg),
      offsetof(sqlite3_api_routines, extended_errcode),
      offsetof(sqlite3_api_routines, randomness),
      offsetof(sqlite3_api_routines, changes),
      offsetof(sqlite3_api_routines, bind_pointer),
      offsetof(sqlite3_api_routines, context_db_handle),
      offsetof(sqlite3_api_routines, result_error_code),
  };
  return index < sizeof(layout) / sizeof(layout[0]) ? layout[index]
                                                    : (size_t)-1;
}
